### ISSUE TITLE
Hard coded Android sdk path

### ISSUE THREAD

**Issue by yogurtearl** [mixpanel/mixpanel-android#273]
run.sh hard codes an SDK path.

```ANDROID_SDK_DIR=~/Library/Android/sdk/```

instead it should honor ANDROID_HOME and fail if ANDROID_HOME is not set.

https://github.com/mixpanel/mixpanel-android/blob/ca5c0d9e74217c6d5ce5e9afa58397c5d1346a14/acceptance/run.sh

**Comment by patedit** [comment]
Thanks for pointing this out @yogurtearl !
This script is only for testing purposes and whoever uses it should know what it's doing. I personally think it makes more sense to let the user modify an script variable than relying on each user to set a global environmental variable in their machines since `ANDROID_HOME` is not set by default.
