### ISSUE TITLE
Android trackCharge() properties not listed into revenue

### ISSUE THREAD

**Issue by nitiwari-dev** [mixpanel/mixpanel-android#281]
I'm sending revenue info to mixpanel using below snippet.

```
   mixPanel.getPeople().identify("myuniqueId");

   JSONObject  prop = new JSONObject();
   prop.put("paymentId", "myId");
   
   mixPanel.getPeople().trackCharge(net_amount, prop) 
```
Cannot find the property **paymentId** into revenue tab ? Any answer is appreciated.

**Comment by ryanseams** [comment]
hi @nitiwari-dev thanks for writing in with this!

when sending a ```mixpanel.getPeople().trackCharge()``` call to Mixpanel, the properties included on the call will not actually be visible within the UI -- these properties will only be available when you export the raw data.

instead, in order to see the properties you wish to segment the revenue tab by, you should send people properties to the specific user who made the transaction using a call like ```mixpanel.getPeople().set()```, ```mixpanel.getPeople().increment()```, ```mixpanel.getPeople().append()```, etc. these are explained in detail [here](https://mixpanel.com/help/reference/android#creating_profiles).

does this help? let me know if i can be of any further assistance here!

**Comment by nitiwari-dev** [comment]
Thanks @ryanseams this was useful.

**Comment by yinfeiru** [comment]
Closing
