### ISSUE TITLE
Now seeing $app_build_number and $app_version_string under "Your Properties"

### ISSUE THREAD

**Issue by jbkielis** [mixpanel/mixpanel-android#328]
"$app_build_number" and "$app_version_string" are now appearing under the "Your Properties" section of each event in the Mixpanel console.  They also appear (as they used to) under the "Mixpanel Properties" section.  

This only appears to be affecting v4.8.

**Comment by yinfeiru** [comment]
Thanks for writing in and I'm glad to know that you are on 4.8 already!!

`$app_build_number` and `$app_version_string` are two new Mixpanel properties we added in this version. The fact that they are under "Your Properties" section is because our website doesn't handle them properly. The Android library itself is behaving properly. I'll update our website to make sure they will display in the proper section in a bit!

**Comment by yinfeiru** [comment]
Please refer to #294 for more info.

**Comment by yinfeiru** [comment]
Closing this as I've created a PR in our private Mixpanel repo and will be shipped shortly.
