### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by ansman** [mixpanel/mixpanel-android#332]
I found that on my Nexus 5X it takes around 200ms to initialize create the mixpanel object. One of the slowest calls (with around 100ms) is the `MPConfig` constructor which tries to create an `SSLSocketFactory`.

This issues has two parts. First, it would be nice if some of the things that are done could be deferred to another thread. Secondly I've started making all my mixpanel calls on a worker thread, will this cause any problems?

**Comment by patedit** [comment]
Hi @ansman ! Certainly 200ms is too much. 
Can the System find a proper SSL support? (i.e. Can your phone get a `SSLContext` instance with `TLS`?). You should see some logs if that is no the case.

There should be no problem if all the calls to our library are made in a separate thread. However, there should be not reason to do so since internally we schedule thread jobs to defer different operations (e.g. `flush`, `track`, etc...).

**Comment by ansman** [comment]
I'm not sure, the timing was found using Nimbledroid so I can't find out what happens there but on my Nexus 5X it gets an SSLContext and creating mixpanel takes around 70ms

**Comment by squeeish** [comment]
@ansman do you have the same in Nimbledroid?

[Imgur](http://i.imgur.com/G9bkKV8.png)

**Comment by ansman** [comment]
@squeeish Yeah, it's similar.

**Comment by squeeish** [comment]
I implemented the following code and improved my startup time. Please do testing though; I don't see issues on my end.

`// initialise Mixpanel
final Context context = this;
AsyncTask.execute(new Runnable() {
    @Override
    public void run() {
	mMixpanel = MixpanelAPI.getInstance(context,getString(R.string.mixpanel_token));
    }
});`

**Comment by Macarse** [comment]
@patedit I see this happening in Fitbit as well.
Check: https://nimbledroid.com/play/com.fitbit.FitbitMobile?p=2ykjol4NupGp1B#Dependencies

MixPanel takes more than 300ms to initialize
