### ISSUE TITLE
Changing Survey Dialog Language

### ISSUE THREAD

**Issue by abhinandankothari** [mixpanel/mixpanel-android#346]
Currently from Strings.xml we have 
 <string name="com_mixpanel_android_survey_prompt_dialog_title">We\'d love your feedback!</string>
    <string name="com_mixpanel_android_survey_prompt_dialog_message">Mind taking a quick survey?</string>
    <string name="com_mixpanel_android_sure">Sure</string>
    <string name="com_mixpanel_android_no_thanks">No, Thanks</string>

How can i change it to Regional language(Bahasa Indonesia) in my case:

"Survey Kesejahteraan"
"Bersedia membantu kami meningkatkan layanan ke dengan mengisi survey?"
"Males ah!" "Soap!"

Thanks

**Comment by ryanseams** [comment]
Hi @abhinandankothari! You can change the language of the survey by including a local copy of the same resource in your project and it will override what is used in the SDK. Specifically, you will want to provide a new value for the string id's you wish to change within your ```strings.xml``` file -- the strings you define will replace what is used by default in the SDK.

You can find a full list of the string id's in our ```strings.xml``` file [here](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/res/values/strings.xml). As an example, if you include a string with id ```com_mixpanel_android_survey_prompt_dialog_title``` whatever value you set for this within your project's ```strings.xml``` file will be used instead of "We\'d love your feedback!"

**Comment by abhinandankothari** [comment]
Thanks a lot :+1: I fixed it and it works. Closing the Issue :)
