### ISSUE TITLE
Tweak.get() always returns the default value

### ISSUE THREAD

**Issue by xlsior** [mixpanel/mixpanel-android#357]
This happens when the app uses multiple instances of the MixpanelAPI, pointing to separate MixPanel projects and only has an experiment running on one of them. This is easily reproducible in the test-application (https://github.com/mixpanel/mixpanel-android/tree/master/acceptance/test-application). Here are the repro steps:

1. You will need to setup two MixPanel projects - Project 1 and Project 2.

2. Make these changes to the sample app:

    Declare a tweak variable and an API key for Project 2
    ```
public static Tweak<String> sTweakTest = MixpanelAPI.stringTweak(
        "Test",
        "default"
    );

public static final String MIXPANEL_API_TOKEN2 = "project 2 token here";
    ```
    Instantiate MixpanelAPI in onCreate()
    ```
mMixpanel = MixpanelAPI.getInstance(this, MIXPANEL_API_TOKEN); 
mMixpanel2 = MixpanelAPI.getInstance(this, MIXPANEL_API_TOKEN2); // add this line for Project #2
    ```
    flush in onDestroy()
    ```
mMixpanel.flush();
mMixpanel2.flush(); // add this line
    ```

3. Create an experiment in Project 1. Set the "Test" tweak in Original to "A", and in Variant 1 to "B". Target Original to 100% of users.

4. sTweakTest.get() always returns "default".

**Comment by ryanseams** [comment]
Whenever you call to grab a Tweak value from ```MixpanelAPI```, it is grabbing that value from the most recently called instance of Mixpanel. As such, the order of the ```getInstance()``` calls matters in terms of applying the right Tweak values.

Is it possible to reverse the order of ```getInstance()``` to initialize ```mMixpanel2``` before ```mMixpanel```? This should result in the behavior you are looking for, where you have multiple Mixpanel instances but the Tweaks are applied based off the of the ```mMixpanel``` values.

**Comment by devorchik** [comment]
The order we are initializing in is correct (anonymous, production) with the tweak variables hanging off production.  I think the underlying bug is when the anonymous result arrives after the production response (from the server), and then becomes data used for the tweaks.

**Comment by ryanseams** [comment]
You are correct -- the issue here is the most recent response from the Mixpanel /decide server is being applied for the Tweak values, regardless of the project. This is made worse by the fact there is no way to specify a Tweak value on a per project basis due to the way Tweaks are defined as global objects of ```MixpanelAPI``` and not tied to any specific project.

While my original solution will work for a simple implementation (for example in a single activity), as you add more activities and send data to different instances the above solution will not be reliable.

A good solution in the library would be to enable Tweaks and/or configuration options on a per project basis and not apply these globally to all instances of ```MixpanelAPI```. That being said, due to the way ```MixpanelAPI``` is structured, this change would require some significant refactoring. Any other ideas here @patedit?

**Comment by devorchik** [comment]
There is likely a cheaper fix to only take the tweaks from the most recent project, e.g. discard those from all but the last call to .getInstance().  Supporting per-project tweaks might desirable down the road, but 2nd to having a predictable behavior on the API.

**Comment by yinfeiru** [comment]
@xlsior https://github.com/mixpanel/mixpanel-android/pull/389 I have a fix for you. With this change, you'll be able to exclude projects from receiving `Tweak` changes. A release with this change is coming out today.
