### ISSUE TITLE
Provide mechanism to use custom HTTP headers

### ISSUE THREAD

**Issue by jishaq** [mixpanel/mixpanel-android#39]
We have our Mixpanel tracking sent to a proxy server for processing, via the BASE_ENDPOINT and FALLBACK_ENDPOINT properties in MPConfig.

Our proxy server requires a custom HTTP header -- specifically, "RDP" -- on all inbound requests.

We have modified HttpPoster.postHttpRequest() to affect this:
```java
httppost.setEntity(new UrlEncodedFormEntity(nameValuePairs));

// ADD OUR CUSTOM HTTP HEADER:
httppost.setHeader("RDP", "true");

HttpResponse response = httpclient.execute(httppost);
```

However, it would be nice to have a mechanism where we can simply supply this to the library, so that we don't have to tweak & build our own version of the lib.

**Comment by yinfeiru** [comment]
This won't be fixed -
1. You have to modify the library and re-build it anyway (since you have to change the endpoint url)
2. The requests are sent to our Mixpanel servers which don't support custom headers
3. Not a lot of users need this feature
4. One line change doesn't seem to be too crazy to me

I'll leave this open for now and close it in a few weeks if no one else asks for it.

**Comment by yinfeiru** [comment]
Actually, since this one is from 2013, I'll close it now. Please create another one if needed.
