### ISSUE TITLE
Noticed Crash in Crashlytics @ com.mixpanel.android.util.HttpService.performRequest(HttpService.java:133)

### ISSUE THREAD

**Issue by alkeshshroff** [mixpanel/mixpanel-android#456]
Hi,

I am using library version 5.0.0 & recently released & update to our application with the new library.

Started noticing crash @ com.mixpanel.android.util.HttpService.performRequest(HttpService.java:133)
This crash is on OS 7.0 & 6.0 and Samsung/HTC/LG devices.

**Fatal Exception: java.lang.InternalError
Thread starting during runtime shutdown**

Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:730)
       at com.android.okhttp.okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:77)
       at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:69)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:216)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:312)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
       at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:81)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:959)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:835)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:422)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:256)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
       at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:133)
       at com.mixpanel.android.mpmetrics.DecideChecker.getUrls(DecideChecker.java:284)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:226)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:1086)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:271)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

There are no steps to reproduce this crash- its only reported in Crashlytics and I see an average of 25 crash per day there.
I can upgrade to 5.0.2 but 5.0.1 or 5.0.2 release notes does not mention that this crash will not occur there.

Please let me know if more details are required.

**Comment by patedit** [comment]
It seems that okhttp library is trying to start a new thread when the VM is shutting down (i.e. the app crashed somewhere else).
This has been discussed [here](https://github.com/ACRA/acra/issues/332) and it seems that okhttp is not going to handle this problem.
The reason why you see this happening from our library and particularly when running a decide request is probably because we are the first ones to make a network request from your app and a crash happens at the startup time (e.g. you init mixpanel on your Application `onCreate` and that triggers a network request to our `decide` server). When that happens, okhttp creates a new thread and that's not allowed since the app already crashed.

I believe that if you don't change your code and just try to make an http request before initializing Mixpanel, the stacktrace will show your http call since that's the first network request and when a new thread is created. I might be wrong since I don't know exactly how and when okhttp creates new threads.

If you want to know what's the real crash that is making the VM to shut down you can fork our library and add a `try/catch` in our `performRequest` method in `HttpService`. That way you will receive the same amount of crashes but at least you'll see the root cause.

Since it seems that the crash happens very early in your app, I'd go through your changes in your Application class (if applicable) and your launcher activity.

Hope that clarifies something and I'm sorry that we can't handle that on our SDK.

**Comment by patedit** [comment]
Another reason why this could be happening is if you are calling `flush()` on `onDestroy()`, the OS kills the app (i.e. low memory) and okhttp creates a new thread on that network call. Notice you don't need to call flush() anymore on `onDestroy()` if you are targeting API 14 and above since we automatically flush when the app goes to the background.
Hope that one of my hints helps you debugging this issue.

**Comment by alkeshshroff** [comment]
@patedit : Thanks for Info 
I do agree with your second comment that calling flush() on onDestroy() can lead to the crash  because OS is in process of killing the app and okHttp creating a new thread can lead to it. I already removed that call from our code.

I do not agree with your first comment that on the start of application the app is crashing and that is leading OkHttp to timeout because if that was the case- crashlytics would have reported the other crash also & even our user would have complained about the same on google play or our support channels.
Our crashlytics reports only mentions this crash. I will create another PR as you mentioned by adding try/catch in performRequest in HttpService.

One question: can you please let me know which Mixpanel API call will call the AnalyticsMessage.handleMessage & execute the code under Install_Decide_Check
`else if (msg.what == INSTALL_DECIDE_CHECK) {
                        logAboutMessageToMixpanel("Installing a check for in-app notifications");
                        final DecideMessages check = (DecideMessages) msg.obj;
                        mDecideChecker.addDecideCheck(check);
                        if (SystemClock.elapsedRealtime() >= mDecideRetryAfter) {
                            try {
                                mDecideChecker.runDecideChecks(getPoster());
                            } catch (RemoteService.ServiceUnavailableException e) {
                                mDecideRetryAfter = SystemClock.elapsedRealtime() + e.getRetryAfter() * 1000;
                            }
                        }
                    }`
Please let me know-
I tried to reproduce this crash multiple time locally but so far no luck.

Thanks
Alkesh Shroff

**Comment by patedit** [comment]
@alkeshshroff Notice that okio is not timing out. The crash occurs when trying to start a thread in `AsyncTimeout.java` while the VM is shutting down. Looking at okio library I'm pretty sure that the thread that is starting is the watchdog thread here: https://github.com/square/okio/blob/master/okio/src/main/java/okio/AsyncTimeout.java#L88

`INSTALL_DECIDE_CHECK` message is sent here: https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L244
That means, every time that you initialize a Mixpanel instance if you have not disabled decide.

I'd fork the library and do a try/catch in `performRequest` for internal debugging so you can find the root cause of your crash.

**Comment by alkeshshroff** [comment]
@patedit : are you planning to create a PR for the try/catch in performRequest & merge it or you want me to do it? btw what exception are you trying to catch there? as library currently catch EOFException & IOException.

**Comment by patedit** [comment]
We are only catching network related exceptions.

I do not feel comfortable catching JVM exceptions in `performRequest` in our public repo. The crash is happening because a third party library (okio) is starting a new thread when the VM is shutting down. Notice that you will have the same problem if you happen to be making any network requests in that moment.

To debug that issue, I proposed you fork the library and add a try/catch so you can see in production what is causing the VM to shut down in your app. Sadly, I can't commit to this change for everyone since it is unrelated to our library. I can help you with that task if you need any help.

Thanks!

**Comment by alkeshshroff** [comment]
@patedit oh so you saying i load local version of Mixpanel library code in my build with try/catch and release that to understand the cause.
As I mentioned earlier, I am not able to reproduce this locally- I also tried causing a crash in my Application onCreate() after the Mixpanel is initialized, still did not see this exception.

Thanks
Alkesh

**Comment by patedit** [comment]
@alkeshshroff Yup. You can fork it using github, modify it and compile it using gradle with jitpack (so you don't need to create a module, etc..).
These crashes are the worst if you can't reproduce them locally, I'm sorry! However, I believe that removing `flush` from `onDestroy` and catching that exception in `performRequest` it's a great start.

**Comment by alkeshshroff** [comment]
@patedit Thank you..!!!!

**Comment by patedit** [comment]
No problem! Let me know how it goes, I'm curious now :)
