### ISSUE TITLE
Tweaks values not always working

### ISSUE THREAD

**Issue by robertoestivill** [mixpanel/mixpanel-android#509]
I'm running into issues displaying values provided by `Tweaks`.
This is an experiment (proof of concept) application.
There are four activities (Screen1-4) and each will retrieve a text value from a Tweak to be displayed on the button.
The Mixpanel sdk and tweaks are being initialized in the android application subclass

```kotlin
class ABTesterApplication : Application() {

  companion object {

    private val tweak1 = MixpanelAPI.stringTweak("screen1_button2", "Default local browser")
    private val tweak2 = MixpanelAPI.stringTweak("screen2_button2", "Default local mobile")
    private val tweak3 = MixpanelAPI.stringTweak("screen3_button2", "Default local city")
    private val tweak4 = MixpanelAPI.stringTweak("screen4_button2", "Default local drink")

    private val tweaks = HashMap<String, Tweak<String>>()
      .apply {
        put("screen1_button2", tweak1)
        put("screen2_button2", tweak2)
        put("screen3_button2", tweak3)
        put("screen4_button2", tweak4)
      }

   fun getStringFromMixpanel(key: String): String {
      val value = tweaks.getValue(key).get()
      Log.d("Mixpanel", "$key = $value")
      return value
    }
  }

  override fun onCreate() {
    super.onCreate()
    MixpanelAPI.getInstance(this, "sfdsfasdfasdfasdfasdfasd")
  }
}
```

The activities will then retrieve the values by statically calling `getStringFromMixpanel()` on the application object, on their `onCreate` lifecycle method. (Also tested with `onResume` with same results)

I have enabled logging and looks like the server returns the correct values for the experiment

```json
{
	"notifications": [],
	"variants": [{
		"tweaks": [{
			"minimum": null,
			"type": "string",
			"name": "screen2_button2",
			"value": "iPhone",
			"maximum": null
		}, {
			"minimum": null,
			"type": "string",
			"name": "screen3_button2",
			"value": "Munich",
			"maximum": null
		}, {
			"minimum": null,
			"type": "string",
			"name": "screen1_button2",
			"value": "Internet Explorer",
			"maximum": null
		}, {
			"minimum": null,
			"type": "string",
			"name": "screen4_button2",
			"value": "Vodka",
			"maximum": null
		}],
		"actions": [],
		"id": 99325,
		"experiment_id": 46947
	}],
	"automatic_events": false,
	"integrations": []
}
```

However, the UI (and the logs in `getStringFromMixpanel()` calls) are returning the default hardcoded values for most of the keys.

```
Activity Screen1
10-20 10:42:31.937  1567  1567 D Mixpanel: screen1_button2 = Default local browser

Activity Screen2
10-20 10:42:35.552  1567  1567 D Mixpanel: screen2_button2 = iPhone

Activity Screen3
10-20 10:42:37.616  1567  1567 D Mixpanel: screen3_button2 = Default local city

Activity Screen4
10-20 10:42:38.996  1567  1567 D Mixpanel: screen4_button2 = Default local drink
```

Is worth mentioning that I have tested with multiple devices in all the experiments buckets, and the results were the same.

Im using the following versions of the dependencies mentioned on the documentation

```
  implementation "com.mixpanel.android:mixpanel-android:5.2.0"
  implementation "com.google.android.gms:play-services-base:11.4.2"
```

Any clues? Thanks

**Comment by patedit** [comment]
Hi @robertoestivill ! Thanks a lot for the thoughtful explanation. Makes things much easier for me! Could you please update your SDK version and use the latest 5.2.1? It should solve your issue :) 
(check the changelog for more details https://github.com/mixpanel/mixpanel-android/wiki/Changelog).

Also, if you want to send push notifications to your users makes sure you include `play-services-gcm` instead of `play-services-base`.

Let me know if you have any other questions!

**Comment by robertoestivill** [comment]
Hi @patedit, thanks for the tip. 
For some reason didn't see that minor version release when I set everything up. 
Will update and report back on Monday.

**Comment by robertoestivill** [comment]
@patedit I can confirm that the version update fixed the problem
For how long are the values stored/cached in the device? Is there anyway to override/configure this?

Thanks for the tip and sorry for the noise in the bug tracker.

**Comment by patedit** [comment]
Glad it worked! Those tweaks are persisted until you remove them from mixpanel.com. Once you remove a tweak, we will fetch the new configuration on the next app open. It will be applied as soon as you background the app. The reason is because we might get the new configuration in the middle of the session and it will be a poor UX if we remove a tweak all of a sudden.

So, let's say that you define a tweak in your code and create a new AB Test and you deploy new tweaks from mixpanel.com. The timeline is as follows:

1. App open
2. Fetch new configuration
3. Persist new configuration
4. Apply new tweaks
5. Remove tweak from mixpanel.com
6. App open
7. Fetch new configuration
8. Persist new configuration
9. Background app
10. Remove tweaks that are no longer used
