### ISSUE TITLE
VeraCode issue in MixPanel android Library

### ISSUE THREAD

**Issue by SandeepAgrawalFluke** [mixpanel/mixpanel-android#575]
We are using Mixpanel library to track events in Mixpanel, we are using VeraCode tool to find security issues, Some issues it has found on Mixpanel library, Request you to check this issues.

Classes and line number on which issue raised : 

1. Improper Output Neutralization for Logs (CWE ID 117)

com/.../android/util/MPLog.java 24

com/.../android/util/MPLog.java 36

com/.../android/util/MPLog.java 72

com/.../android/util/MPLog.java 78

2. Insufficient Entropy (CWE ID 331

com/.../drafts/Draft_10.java 120
com/.../drafts/Draft_10.java 197
com/.../drafts/Draft_75.java 107
com/.../drafts/Draft_76.java 70
com/.../drafts/Draft_76.java 73
com/.../drafts/Draft_76.java 77
com/.../drafts/Draft_76.java 79
com/.../drafts/Draft_76.java 81
com/.../drafts/Draft_76.java 89
com/.../drafts/Draft_76.java 149
com/.../drafts/Draft_76.java 153
com/.../SessionMetadata.java 25
com/.../SessionMetadata.java 40

3. Use of a Broken or Risky Cryptographic Algorithm (CWE ID 327)

com/.../drafts/Draft_10.java 183
com/.../drafts/Draft_76.java 60
com/.../util/ImageStore.java 46
java.lang.String zzb(java.security.KeyPair) 28%

**Comment by SandeepAgrawalFluke** [comment]
Mixpanel team, Any update on this?

**Comment by patedit** [comment]
Hi @SandeepAgrawalFluke - Just want to make sure you understand those don't expose any data nor are risky for our users. I can briefly describe what the mean:

* Insufficient Entropy (CWE ID 331): This is because we are using "random" generated integer/bytes. Every time we use the Random class (and call `nextInt()` or `nextBytes()`). We use those generators to set unique identifiers to events, for example.
* Broken or Risky Cryptographic Algorithm (CWE ID 327): We use sha-1 to store in-app images.
* Improper Output Neutralization for Logs (CWE ID 117): It's flagging our internal logging tool. We don't really need to parse or replace our own logs. They are disabled on prod builds by default, as well.
