### ISSUE TITLE
I can't compile on 5.3.0 using jitpack

### ISSUE THREAD

**Issue by KarlosQ** [mixpanel/mixpanel-android#622]
I'm trying to compile using 5.3.0 version but is like jitpack haven't 5.3.0 already.

Could not HEAD ’https://jitpack.io/com/mixpanel/android/mixpanel-android/5.3.0/mixpanel-android-5.3.0.jar'. Received status code 522 from server: Origin Connection Time-out

I don't want upgrade because I still using GCM.

**Comment by patedit** [comment]
@danielmartinprieto FCM was introduced in release 5.5.0, version 5.3.0 is from February of 2018. Version 5.3.0 is on maven as usual, what error as you seeing on your end? thanks!

**Comment by danielmartinprieto** [comment]
- We were using Jitpack and 5.3.0 has been working for some time without any problem.
- It stopped working recently without any change in our end, I think some problems in Jitpack is causing this (it gives back a wrong http status code and that's why Gradle doesn't fall back into Maven.
- Removing Jitpack made it work again, so I guess `mixpanel-android` wasn't doing anything wrong.

Regarding the semantic versioning of the library, have you considered that removing GCM is a breaking change and therefore you should release a major release instead of a minor one?

Thanks.
