### ISSUE TITLE
"First app open" event 

### ISSUE THREAD

**Issue by maestr0ua** [mixpanel/mixpanel-android#627]
Hello!
Despite the fact that I don't have any special settings in AndroidManifest file, I still get "First App Open" event with random distinctID.
The first question is why I receive that events, even with default value.
```
mDisableAppOpenEvent = metaData.getBoolean("com.mixpanel.android.MPConfig.DisableAppOpenEvent", true);
```
And the second question is why I get that events with random distinctID, despite on that I set my own distinctID at start the application.
```
mixpanelAPI = MixpanelAPI.getInstance(context,context.getString(R.string.mix_panel_token), false);
mixpanelAPI.reset();
mixpanelAPI.getPeople().identify(userId);
mixpanelAPI.identify(userId);
```

I need that events will come with my distinctID or will not come at all. Both variants are appropriate.

Thank you
<img width="1329" alt="Screen Shot 2019-09-12 at 3 11 36 PM-2" src="https://user-images.githubusercontent.com/11719504/65132579-d8e5a400-da09-11e9-96bf-c9b9a5507f7d.png">

**Comment by maestr0ua** [comment]
Could anybody help?

**Comment by patedit** [comment]
Hi @maestr0ua ! That "First App Open" event is one of our default mobile events. If you want to disable this feature, please read [this article](https://help.mixpanel.com/hc/en-us/articles/115004596186-Default-Mobile-Events-Collection).

**Comment by OlivierFreyssinet** [comment]
Hi, sorry to reopen this issue but the linked article's solution is not very satisfying because it's not flexible at all.

Is there really no way to just disable this particular event and not other default mobile events ?

As the OP said, it would be great if at least there was a way to set the `distinctId` **before** this event is sent, because having one event with an ID that will never reappear kind of messes up the analytics ...
For instance if there was a way to get MixpanelAPI instance by specifying the `distinctId` I guess it could solve the issue. I'm saying that because I've seen that in the past, pull requests have been made to specify `superProperties` in `getInstance(...)`. I'm not familiar with the codebase at all so I can't really make that pull request myself for now ...

It also seems strange that the solution to not sending an event _on the client_ is to just filter it out (with other possibly very useful events) in the projects settings ...

This is quite frustrating and if anyone has a solid solution or even a hacky workaround to just force disable this event, I would be super grateful!

**Comment by OlivierFreyssinet** [comment]
Ok actually I managed to implement a working version of the lib that has `getInstance(..., String distinctId)` and sends all events including that "first app open" with `distinctId` so I will probably make a pull request when I have time.
