### ISSUE TITLE
Distinct id and alias confusing

### ISSUE THREAD

**Issue by taimur113311** [mixpanel/mixpanel-android#646]
Hi, 

As i am implementing mixpanel in android app and i am facing 2 issues, please help. 

1: I have changed distinct id after login and user flow is not trackable. is there any way to track events before login and after login with different distinct id's. 
Please check the code on how I change the distinct id. 

>  public synchronized static void setMixPanelIdentifier(Context context, String trackingDistinctId) {

> MixpanelAPI mMixpanel = MixpanelAPI.getInstance(context, BuildConfig.mixpanel_key);

> mMixpanel.identify(trackingDistinctId);

> mMixpanel.getPeople().identify(trackingDistinctId);

> }

2. I am calling .reset() function when the user is logged out but that triggers another next level problem. The device id is changed after calling .reset().
 I want to track multiple profiles on a single device with different people properties and super properties so that I am calling .reset() function but it changed my device id so that I can not maintain multiple profiles on single device. Please suggest me a solution. 

Thanks!

**Comment by cassiegamm** [comment]
Hi @taimur113311,

1) This is a current limitation of the identify method. You can use the [alias](https://developer.mixpanel.com/docs/android#section-combining-anonymous-and-identifiable-user-data) method to link anonymous events with authenticated event when a user creates an account, but this only solve this problem for the user registration funnel. 

We're actively working to update the identify method so that post-login events are linked with pre-login events. We have a solution in private beta and hope to release to the public within a couple months. If you'd like to join the beta, send me an email at identity-mapping@mixpanel.com linking to this Github issue. 

2) Calling reset on logout is almost always the right choice. It's necessary for the SDK to change the device id when reset is called so that each user has a unique profile. If multiple users share the same distinct id, they are effectively the same user. 

It sounds like you may be looking to track a device ID as well as a user ID? If yes, you could achieve your goal by creating a [device specific](https://developer.android.com/training/articles/user-data-ids) GUID and [registering](https://developer.mixpanel.com/docs/android#section-super-properties) it as a property.

hope this helps!
Cassie

**Comment by amitchandelatpstar** [comment]
before login use mixpanel.alias(userId, null)
after login  use mixpanel.identify(userId)

**Comment by cassiegamm** [comment]
If you're project has [ID merge enabled](https://help.mixpanel.com/hc/en-us/articles/360039133851#enable-id-merge), you can use mixpanel.identify(userID) at login and all event history will be stitched together -- no need for alias, and no need to treat signup differently than login.
