### ISSUE TITLE
User properties should be updated without calling some function.

### ISSUE THREAD

**Issue by pyaesone-wm** [mixpanel/mixpanel-android#665]
I think it would be better if we don't need to call some function like mixpanel.people.identity() to flush user properties. According to your Identity management, you can keep identity at login point. And for later pushing user properties, you can develop auto calling that function.

**Comment by patedit** [comment]
Hi @pyaesone-wm - the SDK automatically flushes its queues every 60 seconds by default. You can force a flush by calling `mixpanel.flush()`, as well. Identifying a user profile it is an special operation and we also flush the user queue when that happens, too. But typically you don't need to manually flush since the SDK handles those things for you :)
If you have any other questions let us know please!

**Comment by pyaesone-wm** [comment]
Hi @patedit according to documentation, I know SDK automatically flushes, but sometimes SDK doesn't  update some user properties. As my experience, some properties of some event is updated. But the same properties under user profile ( I mean user property which is the same event property. ) is not updated.

**Comment by patedit** [comment]
@pyaesone-wm sometimes it takes some minutes to have the updated value under user profiles but we haven't heard of dropping updates (it's the core of our business). if you run into issues, could you e-mail support@mixpanel.com ?
