### ISSUE TITLE
[Question] Why RemoteMessage on onMessageReceived doesn't have RemoteMessage.Notification?

### ISSUE THREAD

**Issue by lorenc-tomasz** [mixpanel/mixpanel-android#677]
Hi,
just wondering why RemoteMessage object on onMessageReceived doesn't have RemoteMessage.Notification, so remoteMessage.getNotification() is null? I'm migrating from clean Firebase to mixpanel and it's something that I don't understand.

**Comment by patedit** [comment]
Hi @lorenc-tomasz ! The reason is because Mixpanel sends its own payload and we build our own custom notification. For instance, FCM will try to build a `Notification` from fields such as `gcm.n.icon`, `gcm.n.title` and we send other fields. What do you need the notification for? we expose some members so you can track/inspect notifications.

**Comment by lorenc-tomasz** [comment]
I try to get full control over notifications. I have implementation ready for clean Firebase, so I can have onNotification, onNotificationOpened, etc. listeners.  I have managed to convert mixpanel's payload and recreate proper RemoteMessage with RemoteMessage.Notification object when app is running. The issue I have currently is that I cannot get information if app was opened from notification or if there is pending initial notification when app is opened. Normally I getExtras from getIntent() but with mixpanel the extras is null.

**Comment by lorenc-tomasz** [comment]
Probably the workaround is to send custom data:

```
{"gcm.n.icon": "ic_stat_notif",
"gcm.n.body": "TEST BODY", "gcm.n.title": "TEST TITLE",
"url": "https://google.com"}
```

Then FCM is able to build `Notification` and app get the extras.

**Comment by patedit** [comment]
It seems that you are trying to know whether the app was open from a push notification, correct? Are there any other things you'd like to know?

**Comment by lorenc-tomasz** [comment]
> It seems that you are trying to know whether the app was open from a push notification, correct? 

Correct. 

> Are there any other things you'd like to know?

How to get custom data eg. {"url": "https://google.com"} from the notification when app is opened from this push notification.

**Comment by patedit** [comment]
Great. It seems that the best way to accomplish this is if we add that capability on the SDK.
Until then, I think that the best way to accomplish what you are trying to do is by registering an [activity lifecycle callback](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks) on your application class and check for the intents there. This should work since the SDK creates [this activity](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelNotificationRouteActivity.java) when the user interacts with the push notification and you should have all the information there (intent, extras, etc..). Hope it works!

**Comment by lorenc-tomasz** [comment]
Kinda works. However SDK should have listeners onOpened, onDisplayed, onMessage, etc.

**Comment by lorenc-tomasz** [comment]
@patedit Do you plan adding those callbacks to SDK (similar functionality should be added also to the iOS SDK)?

**Comment by patedit** [comment]
Sorry, we are not planning on adding this for now, but will keep this ticket open in case other folks have the same request.

**Comment by bruscantini** [comment]
Hi. I'm using react-native-mixpanel and running into the same problem. onNotificationOpened and getInitialNotification do not trigger for push notifications sent by Mixpanel dashboard.

It does work for pure FCM messages sent from firebase sdk, though. I can tell if tapping on the notification opened the app and I can see any data sent in the notification.

Does anybody have any insight as to what is required here? Thanks a bunch.

**Comment by lorenc-tomasz** [comment]
The answer is simple - Mixpanel notification doesn't contain all payload data that FCM notification has. You have to create the payload by yourself. 

```
 /* CUSTOM DATA
    {
    "aps":{"content-available":1}, // Required by iOS for Background notification
    "gcm.n.icon": "pw_notification", // Required by Firebase RN lib on Android - use resource name
    "gcm.n.body": "Notification Body", // Required by Firebase RN lib on Android
    "gcm.n.title": "Notification Title", // Required by Firebase  RN lib on Android
    "gcm.n.e": 1, // Required by Firebase RN lib on Android
    "gcm.message_id": "any_random_string" // Required by Firebase RN lib on iOS
    }
```

**Comment by bruscantini** [comment]
@lorenc-tomasz I don't know how to thank you!

**Comment by lorenc-tomasz** [comment]
@bruscantini Happy to helped :) I send some time to support RNFirebase from 5.x to current version. To be honest - I'm not a big fan of Mixpanel push notifications solution. But I need to live with it.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
