### ISSUE TITLE
Error firebase when call init method

### ISSUE THREAD

**Issue by derman10** [mixpanel/mixpanel-android#716]
I am developing an ionic 4 app with Capacitor.
I intend to use mixpanel.
But when init the service:

`this.mixpanel.init(mytoken)`

I'm catching this error in native device (Android 9):

`Default FirebaseApp is not initialized in this process com.catalogo.syngenta. Make sure to call FirebaseApp.initializeApp(Context) first.`
 
Why????
What is the relationship between mixpanel and firebase so that when starting mixpanel it throws me this error?

Btw, only happens in Android. Working fine on iOS platform.

Best Rgs.

Diego

**Comment by zihejia** [comment]
Hi @derman10 , sorry for the late response. This might due to FCM Mixpanel is using to send messages, it needs to be configured(https://developer.mixpanel.com/docs/android-push-notifications). However we are deprecating Messaging and Mobile A/B testing features(more details), please contact our support if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
