### ISSUE TITLE
Google Store rejected app because sending device identifiers

### ISSUE THREAD

**Issue by blueunicorn** [mixpanel/mixpanel-android#769]
Google Store rejected app. Mix panel sdk has sending device identifiers usage.
Please fix it
![image](https://user-images.githubusercontent.com/8372130/143193629-15270608-8c47-48f2-b212-212cfb5ea729.png)

**Comment by zihejia** [comment]
hi @blueunicorn , sorry for the late response. Which version are you using? Mixpanel SDK is not using and sending any of those device identifiers. It might be due to the indirect reference of Google Play Services from firebase cloud messaging(FCM). 

On Jan 1, 2022, we’ll remove the Messages & Experiments feature from Mixpanel [more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/) and release 6.0.0. For now, if you can try 6.0.0-beta-1. We are fully supporting it and encourage you to try.  https://github.com/mixpanel/mixpanel-android/releases/tag/v6.0.0-beta1

**Comment by zihejia** [comment]
hi @blueunicorn , we have released v6.0.0. We should not experience this issue anymore. I'm closing this one now, please feel free to reopen if the problem exists.
